### ISSUE TITLE
feat: Type for null data

### ISSUE THREAD

**Issue by ecojuntak** [bxcodec/goson#11]
**Current version:**
In the current version, if we generate a schema from JSON with null data will cause an error
Example:
```
json = {
  "data": null
}
```

**What I proposed is:**
Checking the value is type of nil, something like this:
```
func getType(item interface{}) string {
	switch item.(type) {
	case string:
		return "string"
	...
	case nil:
		return "nil"
	default:
		var r = reflect.TypeOf(item)
		return fmt.Sprintf("%s", r.String())
	}
}
```

This feature will make sure no error happened when getting null value from response body.

**Comment by bxcodec** [comment]
cool, you can put a PR for this anytime
